import type { FamiliaProduto } from "./tipos.js";

/** Produto siderúrgico plano (cap. 72) — excluído de metal_ferro_aco (utensílio 73). */
export const RE_SIDERURGICO_PLANO =
  /chapa|laminad[oa]?|bobina|\bcoil\b|folha\s+(?:de\s+)?(?:a[cç]o|ferro|steel)|(?:a[cç]o|ferro|steel)\s+folha|hot\s*[- ]?rolled|cold\s*[- ]?rolled|钢板|热轧|冷轧|镀锌|galvaniz(?:ad[oa])?|\bCHP[-_]|(?:steel|metal|a[cç]o|ferro)\s+(?:sheet|plate)|(?:sheet|plate)\s+(?:steel|metal|a[cç]o|ferro)|\d+\s*mm\b/i;

/** ~30 famílias frequentes China→BR — guard-rail de capítulo/posição. */
export const FAMILIAS_PRODUTO: FamiliaProduto[] = [
  {
    id: "iluminacao",
    prefixos: ["9405"],
    re: /lustre|lumin[aá]ria|chandelier|pendente|plafon|wall\s*lamp|aisle\s*light|ceiling\s*light|light\s*fixture|led\s*panel|panel\s*light|吊灯|灯|照明|candelabro|arandela|spot\s*light/i,
    termosBusca: "lustre luminaria eletrica teto parede suspenso LED",
    ncmPreferidos: ["94052100", "94051190", "94051900"],
  },
  {
    id: "moveis_assentos",
    prefixos: ["9401"],
    re: /cadeira|chair|assento|seat|girator|swivel|rotativ|座椅|escritorio|office/i,
    termosBusca: "assento cadeira giratoria escritorio estofada",
    ncmPreferidos: ["94013900", "94013100"],
  },
  {
    id: "moveis_outros",
    prefixos: ["9403"],
    re: /mesa|table|estante|rack|shelf|arm[aá]rio|cabinet|gaveta|drawer|床|桌|柜|家具/i,
    termosBusca: "moveis mesa estante armario madeira metal",
  },
  {
    id: "audio_fones",
    prefixos: ["8518"],
    re: /fone|headphone|headset|earphone|earbud|tws|auscultador|auricular|耳机|耳塞|speaker|alto[- ]?falante/i,
    termosBusca: "fones ouvido auscultador headset microfone",
    ncmPreferidos: ["85183000"],
  },
  {
    id: "telefonia",
    prefixos: ["8517"],
    re: /celular|smartphone|mobile\s*phone|telefone|phone|handset|手机|电话/i,
    termosBusca: "telefone celular smartphone aparelho telefonia",
  },
  {
    id: "cameras",
    prefixos: ["8525", "8528"],
    re: /c[aâ]mera|camera|camcorder|webcam|监控|摄像|录像/i,
    termosBusca: "camera filmadora transmissor imagem video",
    ncmPreferidos: ["85258929", "85258019"],
  },
  {
    id: "cabos_eletricos",
    prefixos: ["8544"],
    re: /cabo|cabos|cable|wire|fio|chicote|harness|电缆|线缆/i,
    termosBusca: "cabos fios condutores isolados electricos",
  },
  {
    id: "recipientes_isotermicos",
    prefixos: ["9617"],
    re: /garrafa\s*t[eé]rm|termic|thermal\s*flask|termo|isot[eé]rm|vacuum\s*flask|vacuum\s*bottle|保温杯|保温瓶/i,
    termosBusca: "garrafa termica recipiente isotermico vacuo",
    ncmPreferidos: ["96170010"],
  },
  {
    id: "plasticos_chapas",
    prefixos: ["3920"],
    re: /pl[aá]stico|polietileno|polipropileno|pvc|acrylic|acrilico|薄膜|塑料|板材/i,
    termosBusca: "placas folhas plastico polietileno",
  },
  {
    id: "plastico_utilidades",
    prefixos: ["3924"],
    re: /utens[ií]lio|houseware|kitchenware|tableware|餐|厨具|塑料杯|塑料碗/i,
    termosBusca: "artigos uso domestico plastico cozinha mesa",
  },
  {
    id: "maquinas_eletricas",
    prefixos: ["8504"],
    re: /transformador|fonte|power\s*supply|conversor|inversor|变压器|电源|适配器|carregador|charger|acumulador/i,
    termosBusca: "transformador conversor estatico fonte alimentacao",
  },
  {
    id: "moto_eletrica",
    prefixos: ["8711"],
    re: /moto\s*el[eé]tr|motocicleta|electric\s*motorcycle|motorcycle|ciclomotor|摩托车/i,
    termosBusca: "motocicleta eletrica motorcycle ciclomotor",
    ncmPreferidos: ["87116000", "87119000"],
  },
  {
    id: "veiculo_leve_eletrico",
    prefixos: ["8711"],
    re: /patinete\s*el[eé]tr|e-?scooter|electric\s*scooter|scooter\s*el[eé]tr|hoverboard|电动滑板车|电动滑板|滑板车|踏板车/i,
    termosBusca: "patinete scooter eletrico veiculo",
    ncmPreferidos: ["87116000", "87119000"],
  },
  {
    id: "brinquedos",
    prefixos: ["9503", "9504", "9505"],
    re: /brinquedo|\btoys?\b|boneca|doll|puzzle|quebra[- ]?cabe[cç]a|building\s+blocks|blocos\s+de\s+montar|figura\s+colecion[aá]vel|collectible\s+figure|action\s+figure|手办|积木|rc\s+toy|carrinho.*controle\s+remoto|controle\s+remoto.*(?:carro|carrinho)|jogo\s+de\s+tabuleiro|board\s+game|jogo\s+infantil|jogo\s+de\s+cartas|card\s+game|game\s+toy|patinete\s+infantil|kick\s*scooter|scooter\s+infantil|玩具|童/i,
    termosBusca: "brinquedo toy infantil diversao boneca puzzle tabuleiro",
    ncmPreferidos: ["95030099", "95030031", "95042000", "95059000"],
  },
  {
    id: "bicicleta",
    prefixos: ["8712"],
    re: /bicicleta|bike|bicycle|ciclismo|自行车|单车/i,
    termosBusca: "bicicleta bike cycle sem motor",
    ncmPreferidos: ["87120010", "87149100"],
  },
  {
    id: "pecas_veiculo_leve",
    prefixos: ["8714", "8708", "7318", "8504"],
    re: /配件|accessories|spare\s*part|pe[cç]a\s*(de|para)?\s*(patinete|scooter|ve[ií]culo|moto)|减震|amortecedor|shock\s*absorber|汽车配件|汽配/i,
    termosBusca: "partes acessorios patinete scooter veiculo leve eletrico autopeças",
    ncmPreferidos: ["87141000", "87089990"],
  },
  {
    id: "filtros_separadores",
    prefixos: ["8421"],
    re: /filtro\s*(de\s*)?(óleo|oleo|combust[ií]vel|ar|lubrificante|hidr[aá]ulic|[aá]gua|water|oil|fuel|air)|oil\s*filter|fuel\s*filter|air\s*filter|water\s*filter|hydraulic\s*filter|elemento\s*filtrante|cartucho\s*filtrante|filter\s*(element|cartridge)|滤清器|滤芯|机油滤|空气滤|燃油滤|柴油滤|油水分离/i,
    termosBusca: "filtro oleo combustivel ar lubrificante elemento filtrante separador 8421",
    ncmPreferidos: ["84212300", "84213100", "84212990", "84219990"],
  },
  {
    id: "autopecas",
    prefixos: ["8708"],
    re: /autope[cç]a|auto\s*part|car\s*part|vehicle\s*part|汽车配件|汽配/i,
    termosBusca: "partes pecas acessorios veiculos automoveis",
  },
  {
    id: "pneus",
    prefixos: ["4011"],
    re: /pneu|tyre|tire|轮胎/i,
    termosBusca: "pneus borracha veiculo",
  },
  {
    id: "parafusos_fixadores",
    prefixos: ["7318"],
    re: /parafus|porca\b|sexav|bolt|screw|nut\b|fixador|fastener|tornillo|螺栓|螺母|螺丝/i,
    termosBusca: "parafusos porcas rebites fixadores metal rosca",
    ncmPreferidos: ["73181500"],
  },
  {
    id: "ferramentas_manual",
    prefixos: ["8205", "8204"],
    re: /jogo\s+de\s+chaves|chave\s+de\s+boca|wrench\s*set|schraubenschl[uü]ssel|schraubendreher|chave\s*(ingl|fenda|phillips|allen)|\bwrench\b|ferramenta\s*manual|hand\s*tool|扳手|螺丝刀/i,
    termosBusca: "ferramentas manuais chaves boca soquetes wrench",
    ncmPreferidos: ["82042000", "82054000"],
  },
  {
    id: "ferramentas_maquina",
    prefixos: ["8204"],
    re: /chave\s*de\s*fenda|chave\s*phillips|chave\s*allen|broca|drill\s*bit|serra\s*copo|ferramenta|tool|扳手/i,
    termosBusca: "ferramentas intercambiaveis brocas chaves",
    ncmPreferidos: ["82042000"],
  },
  {
    id: "ferramentas_eletricas",
    prefixos: ["8467"],
    re: /esmerilhadeira|lixadeira|polidora|winkelschleifer|schleifer|furadeira|parafusadeira|angle\s*grinder|\bgrinder\b|serra\s*el[eé]tr|power\s*tool|电动工具/i,
    termosBusca: "ferramentas eletromecanicas manuais esmerilhadeira lixadeira furadeira",
    ncmPreferidos: ["84672900", "84671190"],
  },
  {
    id: "bombas_ar",
    prefixos: ["8414"],
    re: /fahrradpumpe|luftpumpe|handpumpe|bomba\s+de\s+(ar|bicicleta)|bomba\s+manual|air\s+pump|hand\s+pump|bike\s+pump|floor\s+pump|inflator/i,
    termosBusca: "bombas ar manual bicicleta compressor manual inflador",
    ncmPreferidos: ["84142000", "84142090"],
  },
  {
    id: "bombas_liquido",
    prefixos: ["8413"],
    re: /bomba d['']?[áa]gua|water\s+pump|wasserpumpe|kreiselpumpe|bomba centr[ií]fuga|submersible\s+pump|tauchpumpe/i,
    termosBusca: "bombas liquidos agua centrifuga submersa",
    ncmPreferidos: ["84137010", "84138100"],
  },
  {
    id: "sensores_instrumentos",
    prefixos: ["8536", "9026", "9031"],
    re: /sensor|transdutor|transducer|n[aä]herungssensor|proximity\s+sensor|detector\s+de\s+proximidade/i,
    termosBusca: "sensor transdutor aparelho medicao controle automatico instrumento",
    ncmPreferidos: ["85365090", "90261029", "90318099"],
  },
  {
    id: "cozinha_utensilios",
    prefixos: ["7323", "7324"],
    re: /jogo\s+de\s+panelas|kochtopf|cookware|panelas?\s+(de\s+)?cozinha|conjunto\s+de\s+panelas|topf[- ]?set/i,
    termosBusca: "artigos uso domestico cozinha panelas aco inox ferro",
    ncmPreferidos: ["73239300", "73239400"],
  },
  {
    id: "siderurgico_plano",
    prefixos: ["72"],
    re: RE_SIDERURGICO_PLANO,
    termosBusca: "chapa laminada bobina aco carbono inox galvanizado plano folha",
    ncmPreferidos: ["72085200", "72269200", "72104900", "72193300"],
  },
  {
    id: "metal_ferro_aco",
    prefixos: ["7323", "7326"],
    re: /(?:balde|bucket|tela(?:s)?|mesh|wire\s*cloth|wire\s*screen|grade(?:s)?|grelha|talher|cutlery|colher|garfo|utens[ií]lio(?:s)?|household|domestic|artigo(?:s)?\s+(?:de\s+)?(?:dom[eé]stic|ferro|a[cç]o|inox)|pe[cç]a(?:s)?\s+(?:de\s+)?a[cç]o|pe[cç]a\s+a[cç]o|prego|tacha|rebite)/i,
    termosBusca: "artigos ferro aco inox uso domestico balde tela talher",
  },
  {
    id: "aluminio",
    prefixos: ["7615"],
    re: /alum[ií]nio|aluminum|aluminium|铝/i,
    termosBusca: "artigos aluminio mesa cozinha",
    ncmPreferidos: ["76151000"],
  },
  {
    id: "textil_vestuario",
    prefixos: ["61", "62"],
    re: /camiseta|t-?shirt|shirt|blusa|dress|vestido|cal[cç]a|pants|roupa|clothing|garment|服装|衣/i,
    termosBusca: "vestuario confeccao malha tecido",
  },
  {
    id: "textil_cama_mesa",
    prefixos: ["63"],
    re: /toalha|towel|len[cç]ol|sheet|curtain|cortina|cotton|algod[aã]o|jogo\s+de\s+len[cç]ol|jogo\s+de\s+cama|bed\s+linen\s+set|kit\s+de\s+len[cç]ol|棉|布/i,
    termosBusca: "artigos texteis cama mesa banho",
  },
  {
    id: "medico",
    prefixos: ["9018", "9019"],
    re: /m[eé]dic|medical|hospital|massage|massagem|term[oô]metro|thermometer|医疗|按摩/i,
    termosBusca: "aparelhos instrumentos medicos massagem",
    ncmPreferidos: ["90191000"],
  },
  {
    id: "cosmeticos",
    prefixos: ["33"],
    re: /cosm[eé]t|makeup|perfume|creme|lotion|skincare|化妆|护肤/i,
    termosBusca: "cosmeticos perfumaria cuidados pele",
  },
  {
    id: "sabonetes",
    prefixos: ["3401"],
    re: /sab[aã]o|soap|detergent|detergente|洗涤/i,
    termosBusca: "saboes detergentes organicos",
  },
  {
    id: "malas_bolsas",
    prefixos: ["4202"],
    re: /bolsa|bag|mala|suitcase|backpack|mochila|wallet|carteira|包|袋/i,
    termosBusca: "malas bolsas couro viagem",
    ncmPreferidos: ["42029200"],
  },
  {
    id: "eletrodomesticos",
    prefixos: ["8509", "8510", "8516"],
    re: /liquidificador|blender|aspirador|vacuum|ferro\s*passar|iron|fog[aã]o|stove|mixer|juicer|榨汁/i,
    termosBusca: "eletrodomestico cozinha limpeza",
  },
  {
    id: "aparelhos_eletricos",
    prefixos: ["8536", "8537"],
    re: /disjuntor|circuit\s*breaker|switch|interruptor|tomada|socket|relay|rel[eé]|配电/i,
    termosBusca: "aparelhos protecao circuito interruptores",
    ncmPreferidos: ["85366100"],
  },
  {
    id: "embalagem_papel",
    prefixos: ["4819", "3923"],
    re: /caixa|box|carton|embalagem|packaging|paper\s*bag|sacola|papel[aã]o|纸箱|包装/i,
    termosBusca: "embalagens caixas papel plastico",
  },
  {
    id: "eletro_portatil",
    prefixos: ["8509", "8508"],
    re: /eletrodom[eé]stico|aparelho\s*el[eé]tr|electrical\s*appliance|家用/i,
    termosBusca: "aparelho eletromecanico uso domestico",
    ncmPreferidos: ["85098090"],
  },
];
